'use client';

import { createContext, useContext, useEffect, useState } from 'react';

const LanguageContext = createContext(null);

const STORAGE_KEY = 'language';
const SUPPORTED = ['en', 'lt'];

const translations = {
  en: {
    // Sidebar
    'nav.overview':       'OVERVIEW',
    'nav.lessons':        'LESSONS',
    'nav.discover':       'DISCOVER',
    'nav.dashboard':      'Dashboard',
    'nav.messages':       'Messages',
    'nav.myLessons':      'My Lessons',
    'nav.inviteTeacher':  'Invite Teacher',
    'nav.adminOverview':  'Overview',
    'nav.profileSettings':'Profile settings',
    'nav.signOut':        'Sign out',

    // Common
    'common.save':        'Save Changes',
    'common.saving':      'Saving…',
    'common.saved':       'Saved!',
    'common.error':       'Error — retry',
    'common.cancel':      'Cancel',
    'common.loading':     'Loading…',
    'common.viewAll':     'View all →',
    'common.expand':      'Expand',
    'common.collapse':    'Collapse',

    // Topbar / language toggle
    'lang.toggleTitle':   'Switch language',

    // Dashboard
    'dashboard.crumb':           'Dashboard',
    'dashboard.kicker':          'Dashboard',
    'dashboard.welcome':         'Welcome back.',
    'dashboard.subtitleTeacher': "Here's your week at a glance and pending lesson requests.",
    'dashboard.subtitleStudent': 'Track your lesson requests and find new tutors.',
    'dashboard.upcoming':        'Upcoming lessons',
    'dashboard.completed':       'Lessons completed',
    'dashboard.myLessons':       'My Lessons',
    'dashboard.myLessonsSub':    'Lessons your tutor has scheduled.',
    'dashboard.noLessons':       'No lessons yet',
    'dashboard.noLessonsHint':   'Your tutor schedules your lessons — they will appear here.',
    'dashboard.calendar':        'Lesson Calendar',
    'dashboard.calendarSub':     'All requests, accepted and rejected lessons.',
    'dashboard.pendingTitle':    'Pending Requests',
    'dashboard.proposedTitle':   'Lessons your tutor proposed',
    'dashboard.notes':           'Notes',
    'dashboard.struggles':       'Struggles with',
    'dashboard.expects':         'Expects',
    'dashboard.accept':          'Accept',
    'dashboard.reject':          'Reject',
    'dashboard.student':         'Student',
    'dashboard.teacher':         'Teacher',

    // Lesson detail modal
    'lessonDetail.title':       'Lesson details',
    'lessonDetail.when':        'When',
    'lessonDetail.grade':       'Grade / level',
    'lessonDetail.contact':     'Contact',
    'lessonDetail.phone':       'Phone',
    'lessonDetail.subject':     'Subject',
    'lessonDetail.subjects':    'Subjects',
    'lessonDetail.tags':        'Topics',
    'lessonDetail.aboutTutor':  'About the tutor',
    'lessonDetail.payment':        'Payment',
    'lessonDetail.paid':           'Paid',
    'lessonDetail.unpaid':         'Awaiting payment',
    'lessonDetail.payInstructions':'Send a bank transfer for this lesson to:',
    'lessonDetail.paymentRef':     'Payment reference',
    'lessonDetail.amount':         'Amount',
    'lessonDetail.payee':          'Account holder',
    'lessonDetail.noBilling':      'The payment account has not been set up yet. Ask an administrator.',
    'lessonDetail.markPaid':       'Mark as paid',
    'lessonDetail.noStudentInfo': 'This student hasn\'t added profile details yet.',
    'lessonDetail.noTutorInfo':   'This tutor hasn\'t added profile details yet.',
    'lessonDetail.close':       'Close',
    'lessonDetail.join':        'Join lesson',
    'lessonDetail.startsIn':    'Starts in',
    'lessonDetail.live':        'Live now',
    'lessonDetail.ended':       'Lesson ended',
    'lessonDetail.lessonRoom':  'Lesson room',

    // Status
    'status.pending':  'Pending',
    'status.accepted': 'Accepted',
    'status.rejected': 'Rejected',

    // Profile
    'profile.crumb':           'Profile Settings',
    'profile.kicker':          'Profile Settings',
    'profile.title':           'Profile Settings',
    'profile.subtitleTeacher': 'Complete your profile so students can find and book you.',
    'profile.subtitleStudent': 'Manage your basic account details.',
    'profile.preview':         'Preview Profile',
    'profile.basic':           'Basic Information',
    'profile.aboutStudent':    'About You',
    'profile.aboutStudentSub': 'Share a bit about yourself so teachers can prepare for your lesson.',
    'profile.photo':           'Photo',
    'profile.upload':          'Upload photo',
    'profile.uploading':       'Uploading…',
    'profile.fullName':        'Full name',
    'profile.fullNamePh':      'Your full name',
    'profile.phone':           'Phone number',
    'profile.phonePh':         '+370 6XX XXXXX',
    'profile.phoneRequired':   'Please enter your phone number.',
    'profile.headline':        'Headline',
    'profile.grade':           'Grade / level',
    'profile.gradePh':         'e.g. 10th grade · IB Year 1 · University freshman',
    'profile.struggles':       "What's hardest to understand?",
    'profile.strugglesPh':     'Topics or concepts you struggle with — e.g. quadratic equations, essay structure…',
    'profile.expectations':    'What do you expect from lessons?',
    'profile.expectationsPh':  'What outcome are you aiming for — pass an exam, build confidence, prep for a test?',

    // Create lesson
    'create.subject':       'Subject',
    'create.subjectPh':     'Choose a subject',
    'create.date':          'Date',
    'create.time':          'Time (24h)',
    'create.notes':         'Notes (optional)',
    'create.notesPh':       'Topic you want to cover, things you struggle with, etc.',
    'create.notSet':        'Date and time not set',

    // Schedule lesson page (teacher)
    'schedule.crumb':          'Schedule Lesson',
    'schedule.price':          'Lesson price',
    'schedule.priceHint':      'What you earn for this lesson. Leave blank if it is free.',
    'schedule.noPrice':        'No price set',
    'schedule.noAssigned':     'No students have signed up yet.',
    'schedule.kicker':         'Schedule Lesson',
    'schedule.title':          'Schedule a Lesson',
    'schedule.subtitle':       'Pick a student and set a time. The lesson is confirmed right away.',
    'schedule.create':         'Create Lesson',
    'schedule.sending':        'Creating…',
    'schedule.student':        'Student',
    'schedule.selectStudent':  'Select a student',
    'schedule.preview':        'Lesson Preview',
    'schedule.noStudent':      'No student selected',

    // Lessons page
    'lessons.crumb':            'My Lessons',
    'lessons.kicker':           'My Lessons',
    'lessons.title':            'My Lessons',
    'lessons.subtitleTeacher':  'Incoming lesson requests and your scheduled sessions.',
    'lessons.subtitleStudent':  'Track every lesson request you have sent.',
    'lessons.scheduleLesson':   'Schedule Lesson',
    'lessons.viewList':         'List',
    'lessons.viewCalendar':     'Calendar',
    'lessons.noLessons':        'No lessons yet',
    'lessons.noPending':        'No pending lessons',
    'lessons.noAccepted':       'No accepted lessons',
    'lessons.noRejected':       'No rejected lessons',
    'lessons.tabAll':           'All',
    'lessons.tabPending':       'Pending',
    'lessons.tabAccepted':      'Accepted',
    'lessons.tabRejected':      'Rejected',
    'lessons.unknown':          'Unknown',
    'lessons.accept':           'Accept',
    'lessons.reject':           'Reject',
    'lessons.cancel':           'Cancel',
    'lessons.join':             'Join lesson',
    'lessons.failedLoad':       'Failed to load lessons.',
    'lessons.failedUpdate':     'Failed to update lesson.',

    // Messages page
    'messages.crumb':              'Messages',
    'messages.kicker':             'Messages',
    'messages.title':              'Conversations',
    'messages.subtitle':           'Talk to the tutors and students you share lessons with.',
    'messages.listHeader':         'Conversations',
    'messages.noConversations':    'No conversations yet.',
    'messages.startHint':          'Book or accept a lesson to start chatting.',
    'messages.unknown':            'Unknown',
    'messages.noMessagesYetShort': 'No messages yet',
    'messages.selectConversation': 'Select a conversation',
    'messages.sayHi':              'No messages yet — say hi.',
    'messages.placeholder':        'Write a message…',
    'messages.sending':            'Sending…',
    'messages.send':               'Send',
    'messages.rlsError':           'You can only message people you share a lesson with.',
    'messages.failedLoadConvs':    'Failed to load conversations.',
    'messages.failedLoadMessages': 'Failed to load messages.',
    'messages.failedSend':         'Failed to send message.',

    // Lesson detail modal — extras
    'lessonDetail.openExternalMeet': 'Open external Meet',
    'lessonDetail.message':          'Message',
    'lessonDetail.board':            'Open saved whiteboard',
    'board.kicker':                  'Saved whiteboard',
    'board.lesson':                  'Lesson',
    'board.back':                    'Back to lessons',
    'lessonDetail.tutorWord':        'tutor',
    'lessonDetail.studentWord':      'student',

    // Teacher stats / earnings
    'stats.taught':           'Lessons taught',
    'stats.taughtHint':       'Accepted lessons whose time has passed.',
    'stats.earned':           'Earned',
    'stats.earnedHint':       'Total price of lessons taught.',
    'stats.received':         'Received',
    'stats.receivedHint':     'Confirmed as paid.',
    'stats.outstanding':      'Outstanding',
    'stats.outstandingHint':  'Taught but not yet confirmed paid.',
    'stats.upcoming':         'Upcoming lessons',
    'stats.upcomingHint':     'Scheduled and still ahead.',
    'stats.rating':           'Rating',
    'stats.noRatings':        'No ratings yet.',
    'stats.ofReviews':        '{n} ratings',
    'stats.recentFeedback':   'Recent feedback',
    'stats.unpricedWarning':  '{n} lessons taught have no price set, so they are not counted in the totals.',

    // Ratings
    'rating.rateThis':        'Rate this lesson',
    'rating.yourRating':      'Your rating',
    'rating.studentRated':    'Student rating',
    'rating.submit':          'Submit rating',
    'rating.update':          'Update rating',
    'rating.canChange':       'You can change this at any time.',
    'rating.visibleToTutor':  'Your tutor sees this rating and who left it.',
    'rating.commentPlaceholder': 'Anything you want to add? (optional)',
    'rating.failed':          'Could not save your rating.',
    'rating.rateRecent':      'Rate your lessons',
    'rating.rateRecentSub':   'Let your tutor know how it went.',
    'rating.nothingToRate':   'Nothing to rate yet.',

    // Admin overview
    'admin.crumb':            'Overview',
    'admin.kicker':           'Administration',
    'admin.title':            'Teacher overview',
    'admin.subtitle':         'Every teacher’s lessons, earnings and rating, plus who they may teach.',
    'admin.totalTeachers':    'Teachers',
    'admin.totalTaught':      'Lessons taught',
    'admin.totalEarned':      'Total earned',
    'admin.totalOutstanding': 'Total outstanding',
    'admin.teachers':         'Teachers',
    'admin.teachersSub':      'Open a teacher to see their dashboard and free hours.',
    'admin.noTeachers':       'No teachers yet. Invite one first.',
    'admin.availability':     'Free hours',
    'admin.noAvailability':   'This teacher has not marked any free hours yet.',
    'admin.billingTitle':     'Payment account',
    'admin.billingSub':       'The single account students are asked to transfer to, whoever teaches the lesson. Only administrators can change it.',
    'admin.iban':             'IBAN',
    'admin.holder':           'Account holder',
    'admin.bankName':         'Bank',
    'admin.note':             'Note for students',
    'admin.notePh':           'e.g. include the payment reference in the transfer description',
    'admin.billingFailed':    'Could not save payment details.',
    'admin.loadFailed':       'Could not load the overview.',
    'admin.saveFailed':       'Could not save that change.',
  },

  lt: {
    // Sidebar
    'nav.overview':       'APŽVALGA',
    'nav.lessons':        'PAMOKOS',
    'nav.discover':       'ATRASKITE',
    'nav.dashboard':      'Skydelis',
    'nav.messages':       'Žinutės',
    'nav.myLessons':      'Mano pamokos',
    'nav.inviteTeacher':  'Pakviesti mokytoją',
    'nav.adminOverview':  'Apžvalga',
    'nav.profileSettings':'Profilio nustatymai',
    'nav.signOut':        'Atsijungti',

    // Common
    'common.save':        'Išsaugoti pakeitimus',
    'common.saving':      'Išsaugoma…',
    'common.saved':       'Išsaugota!',
    'common.error':       'Klaida — bandykite dar kartą',
    'common.cancel':      'Atšaukti',
    'common.loading':     'Kraunama…',
    'common.viewAll':     'Žiūrėti visus →',
    'common.expand':      'Išskleisti',
    'common.collapse':    'Suskleisti',

    // Topbar / language toggle
    'lang.toggleTitle':   'Keisti kalbą',

    // Dashboard
    'dashboard.crumb':           'Skydelis',
    'dashboard.kicker':          'Skydelis',
    'dashboard.welcome':         'Sveiki sugrįžę.',
    'dashboard.subtitleTeacher': 'Čia jūsų savaitės apžvalga ir laukiančios pamokų užklausos.',
    'dashboard.subtitleStudent': 'Sekite savo pamokų užklausas ir raskite naujų korepetitorių.',
    'dashboard.upcoming':        'Artimiausios pamokos',
    'dashboard.completed':       'Pravesta pamokų',
    'dashboard.myLessons':       'Mano pamokos',
    'dashboard.myLessonsSub':    'Pamokos, kurias suplanavo korepetitorius.',
    'dashboard.noLessons':       'Pamokų dar nėra',
    'dashboard.noLessonsHint':   'Pamokas planuoja korepetitorius — jos atsiras čia.',
    'dashboard.calendar':        'Pamokų kalendorius',
    'dashboard.calendarSub':     'Visos užklausos, priimtos ir atmestos pamokos.',
    'dashboard.pendingTitle':    'Laukiančios užklausos',
    'dashboard.proposedTitle':   'Korepetitoriaus pasiūlytos pamokos',
    'dashboard.notes':           'Pastabos',
    'dashboard.struggles':       'Sunkiai sekasi',
    'dashboard.expects':         'Tikisi',
    'dashboard.accept':          'Priimti',
    'dashboard.reject':          'Atmesti',
    'dashboard.student':         'Mokinys',
    'dashboard.teacher':         'Korepetitorius',

    // Lesson detail modal
    'lessonDetail.title':       'Pamokos informacija',
    'lessonDetail.when':        'Kada',
    'lessonDetail.grade':       'Klasė / lygis',
    'lessonDetail.contact':     'El. paštas',
    'lessonDetail.phone':       'Telefonas',
    'lessonDetail.subject':     'Dalykas',
    'lessonDetail.subjects':    'Dalykai',
    'lessonDetail.tags':        'Temos',
    'lessonDetail.aboutTutor':  'Apie korepetitorių',
    'lessonDetail.payment':        'Mokėjimas',
    'lessonDetail.paid':           'Apmokėta',
    'lessonDetail.unpaid':         'Laukiama apmokėjimo',
    'lessonDetail.payInstructions':'Atlikite pavedimą už šią pamoką į:',
    'lessonDetail.paymentRef':     'Mokėjimo paskirtis',
    'lessonDetail.amount':         'Suma',
    'lessonDetail.payee':          'Sąskaitos savininkas',
    'lessonDetail.noBilling':      'Atsiskaitomoji sąskaita dar nenustatyta. Kreipkitės į administratorių.',
    'lessonDetail.markPaid':       'Pažymėti apmokėta',
    'lessonDetail.noStudentInfo': 'Šis mokinys dar neužpildė profilio.',
    'lessonDetail.noTutorInfo':   'Šis korepetitorius dar neužpildė profilio.',
    'lessonDetail.close':       'Uždaryti',
    'lessonDetail.join':        'Prisijungti prie pamokos',
    'lessonDetail.startsIn':    'Prasidės po',
    'lessonDetail.live':        'Vyksta dabar',
    'lessonDetail.ended':       'Pamoka pasibaigė',
    'lessonDetail.lessonRoom':  'Pamokos kambarys',

    // Status
    'status.pending':  'Laukia',
    'status.accepted': 'Priimta',
    'status.rejected': 'Atmesta',

    // Profile
    'profile.crumb':           'Profilio nustatymai',
    'profile.kicker':          'Profilio nustatymai',
    'profile.title':           'Profilio nustatymai',
    'profile.subtitleTeacher': 'Užpildykite profilį, kad mokiniai galėtų jus rasti ir užsakyti pamoką.',
    'profile.subtitleStudent': 'Tvarkykite pagrindinius paskyros duomenis.',
    'profile.preview':         'Peržiūrėti profilį',
    'profile.basic':           'Pagrindinė informacija',
    'profile.aboutStudent':    'Apie jus',
    'profile.aboutStudentSub': 'Papasakokite apie save, kad korepetitorius galėtų pasiruošti pamokai.',
    'profile.photo':           'Nuotrauka',
    'profile.upload':          'Įkelti nuotrauką',
    'profile.uploading':       'Įkeliama…',
    'profile.fullName':        'Vardas ir pavardė',
    'profile.fullNamePh':      'Jūsų vardas ir pavardė',
    'profile.phone':           'Telefono numeris',
    'profile.phonePh':         '+370 6XX XXXXX',
    'profile.phoneRequired':   'Įveskite savo telefono numerį.',
    'profile.headline':        'Antraštė',
    'profile.grade':           'Klasė / lygis',
    'profile.gradePh':         'pvz. 10 klasė · IB 1 metai · I kurso studentas',
    'profile.struggles':       'Kas sunkiausiai suprantama?',
    'profile.strugglesPh':     'Temos ar sąvokos, su kuriomis sunku — pvz. kvadratinės lygtys, rašinio struktūra…',
    'profile.expectations':    'Ko tikitės iš pamokų?',
    'profile.expectationsPh':  'Kokio rezultato siekiate — išlaikyti egzaminą, įgyti pasitikėjimo, pasiruošti testui?',

    // Create lesson
    'create.subject':       'Dalykas',
    'create.subjectPh':     'Pasirinkite dalyką',
    'create.date':          'Data',
    'create.time':          'Laikas (24 val.)',
    'create.notes':         'Pastabos (neprivaloma)',
    'create.notesPh':       'Tema, kurią norite aptarti, su kuo susiduriate ir t. t.',
    'create.notSet':        'Data ir laikas nenustatyti',

    // Schedule lesson page (teacher)
    'schedule.crumb':          'Suplanuoti pamoką',
    'schedule.price':          'Pamokos kaina',
    'schedule.priceHint':      'Kiek uždirbate už šią pamoką. Palikite tuščią, jei nemokama.',
    'schedule.noPrice':        'Kaina nenurodyta',
    'schedule.noAssigned':     'Platformoje dar nėra užsiregistravusių mokinių.',
    'schedule.kicker':         'Suplanuoti pamoką',
    'schedule.title':          'Suplanuoti pamoką',
    'schedule.subtitle':       'Pasirinkite mokinį ir laiką. Pamoka bus iškart patvirtinta.',
    'schedule.create':         'Sukurti pamoką',
    'schedule.sending':        'Kuriama…',
    'schedule.student':        'Mokinys',
    'schedule.selectStudent':  'Pasirinkite mokinį',
    'schedule.preview':        'Pamokos peržiūra',
    'schedule.noStudent':      'Mokinys nepasirinktas',

    // Lessons page
    'lessons.crumb':            'Mano pamokos',
    'lessons.kicker':           'Mano pamokos',
    'lessons.title':            'Mano pamokos',
    'lessons.subtitleTeacher':  'Gautos pamokų užklausos ir suplanuoti susitikimai.',
    'lessons.subtitleStudent':  'Sekite visas išsiųstas pamokų užklausas.',
    'lessons.scheduleLesson':   'Suplanuoti pamoką',
    'lessons.viewList':         'Sąrašas',
    'lessons.viewCalendar':     'Kalendorius',
    'lessons.noLessons':        'Pamokų dar nėra',
    'lessons.noPending':        'Laukiančių pamokų nėra',
    'lessons.noAccepted':       'Priimtų pamokų nėra',
    'lessons.noRejected':       'Atmestų pamokų nėra',
    'lessons.tabAll':           'Visos',
    'lessons.tabPending':       'Laukia',
    'lessons.tabAccepted':      'Priimtos',
    'lessons.tabRejected':      'Atmestos',
    'lessons.unknown':          'Nežinomas',
    'lessons.accept':           'Priimti',
    'lessons.reject':           'Atmesti',
    'lessons.cancel':           'Atšaukti',
    'lessons.join':             'Prisijungti',
    'lessons.failedLoad':       'Nepavyko įkelti pamokų.',
    'lessons.failedUpdate':     'Nepavyko atnaujinti pamokos.',

    // Messages page
    'messages.crumb':              'Žinutės',
    'messages.kicker':             'Žinutės',
    'messages.title':              'Pokalbiai',
    'messages.subtitle':           'Bendraukite su korepetitoriais ir mokiniais, su kuriais turite bendrą pamoką.',
    'messages.listHeader':         'Pokalbiai',
    'messages.noConversations':    'Pokalbių dar nėra.',
    'messages.startHint':          'Užsakykite arba priimkite pamoką, kad galėtumėte rašyti.',
    'messages.unknown':            'Nežinomas',
    'messages.noMessagesYetShort': 'Žinučių dar nėra',
    'messages.selectConversation': 'Pasirinkite pokalbį',
    'messages.sayHi':              'Žinučių dar nėra — pasisveikinkite.',
    'messages.placeholder':        'Parašykite žinutę…',
    'messages.sending':            'Siunčiama…',
    'messages.send':               'Siųsti',
    'messages.rlsError':           'Galite rašyti tik tiems, su kuriais turite bendrą pamoką.',
    'messages.failedLoadConvs':    'Nepavyko įkelti pokalbių.',
    'messages.failedLoadMessages': 'Nepavyko įkelti žinučių.',
    'messages.failedSend':         'Nepavyko išsiųsti žinutės.',

    // Lesson detail modal — extras
    'lessonDetail.openExternalMeet': 'Atidaryti išorinį Meet',
    'lessonDetail.message':          'Rašyti',
    'lessonDetail.board':            'Atidaryti išsaugotą lentą',
    'board.kicker':                  'Išsaugota lenta',
    'board.lesson':                  'Pamoka',
    'board.back':                    'Atgal į pamokas',
    'lessonDetail.tutorWord':        'korepetitoriui',
    'lessonDetail.studentWord':      'mokiniui',

    // Teacher stats / earnings
    'stats.taught':           'Pravesta pamokų',
    'stats.taughtHint':       'Patvirtintos pamokos, kurių laikas jau praėjo.',
    'stats.earned':           'Uždirbta',
    'stats.earnedHint':       'Bendra pravestų pamokų kaina.',
    'stats.received':         'Gauta',
    'stats.receivedHint':     'Patvirtinta kaip apmokėta.',
    'stats.outstanding':      'Neapmokėta',
    'stats.outstandingHint':  'Pravesta, bet mokėjimas dar nepatvirtintas.',
    'stats.upcoming':         'Būsimos pamokos',
    'stats.upcomingHint':     'Suplanuotos ir dar nepravestos.',
    'stats.rating':           'Reitingas',
    'stats.noRatings':        'Įvertinimų dar nėra.',
    'stats.ofReviews':        '{n} įvertinimų',
    'stats.recentFeedback':   'Naujausi atsiliepimai',
    'stats.unpricedWarning':  '{n} pravestoms pamokoms nenurodyta kaina, todėl jos neįskaičiuotos į sumas.',

    // Ratings
    'rating.rateThis':        'Įvertinkite pamoką',
    'rating.yourRating':      'Jūsų įvertinimas',
    'rating.studentRated':    'Mokinio įvertinimas',
    'rating.submit':          'Pateikti įvertinimą',
    'rating.update':          'Atnaujinti įvertinimą',
    'rating.canChange':       'Bet kada galite pakeisti.',
    'rating.visibleToTutor':  'Jūsų korepetitorius mato šį įvertinimą ir kas jį parašė.',
    'rating.commentPlaceholder': 'Norėtumėte ką nors pridėti? (neprivaloma)',
    'rating.failed':          'Nepavyko išsaugoti įvertinimo.',
    'rating.rateRecent':      'Įvertinkite pamokas',
    'rating.rateRecentSub':   'Pasakykite korepetitoriui, kaip sekėsi.',
    'rating.nothingToRate':   'Kol kas nėra ką vertinti.',

    // Admin overview
    'admin.crumb':            'Apžvalga',
    'admin.kicker':           'Administravimas',
    'admin.title':            'Mokytojų apžvalga',
    'admin.subtitle':         'Kiekvieno mokytojo pamokos, uždarbis ir reitingas bei jiems priskirti mokiniai.',
    'admin.totalTeachers':    'Mokytojai',
    'admin.totalTaught':      'Pravesta pamokų',
    'admin.totalEarned':      'Bendras uždarbis',
    'admin.totalOutstanding': 'Iš viso neapmokėta',
    'admin.teachers':         'Mokytojai',
    'admin.teachersSub':      'Atidarykite mokytoją, kad matytumėte jo skydelį ir laisvus laikus.',
    'admin.noTeachers':       'Mokytojų dar nėra. Pirmiausia pakvieskite.',
    'admin.availability':     'Laisvi laikai',
    'admin.noAvailability':   'Šis mokytojas dar nenurodė laisvų laikų.',
    'admin.billingTitle':     'Atsiskaitomoji sąskaita',
    'admin.billingSub':       'Viena sąskaita, į kurią moka visi mokiniai, nesvarbu, kas veda pamoką. Keisti gali tik administratoriai.',
    'admin.iban':             'IBAN',
    'admin.holder':           'Sąskaitos savininkas',
    'admin.bankName':         'Bankas',
    'admin.note':             'Pastaba mokiniams',
    'admin.notePh':           'pvz., pavedimo paskirtyje nurodykite mokėjimo kodą',
    'admin.billingFailed':    'Nepavyko išsaugoti mokėjimo duomenų.',
    'admin.loadFailed':       'Nepavyko įkelti apžvalgos.',
    'admin.saveFailed':       'Nepavyko išsaugoti pakeitimo.',
  },
};

export function LanguageProvider({ children }) {
  const [lang, setLangState] = useState('en');

  useEffect(() => {
    if (typeof window === 'undefined') return;
    const stored = localStorage.getItem(STORAGE_KEY);
    if (SUPPORTED.includes(stored)) setLangState(stored);
  }, []);

  const setLang = (next) => {
    if (!SUPPORTED.includes(next)) return;
    if (typeof window !== 'undefined') localStorage.setItem(STORAGE_KEY, next);
    setLangState(next);
  };

  const t = (key) => translations[lang]?.[key] ?? translations.en[key] ?? key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext) ?? { lang: 'en', setLang: () => {}, t: (k) => k };
}
